## Project 4 - Kaggle Competition Starter Code (West Nile Virus Detection)

In [29]:
import pandas as pd
import numpy as np

In [180]:
weather = pd.read_csv("../assets/weather.csv")
weather.head()

,Station,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,...,CodeSum,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,1,2007-05-01,83,50,67,14,51,56,0,2,...,,0,M,0.0,0.00,29.10,29.82,1.7,27,9.2
1,2,2007-05-01,84,52,68,M,51,57,0,3,...,,M,M,M,0.00,29.18,29.82,2.7,25,9.6
2,1,2007-05-02,59,42,51,-3,42,47,14,0,...,BR,0,M,0.0,0.00,29.38,30.09,13.0,4,13.4
3,2,2007-05-02,60,43,52,M,42,47,13,0,...,BR HZ,M,M,M,0.00,29.44,30.08,13.3,2,13.4
4,1,2007-05-03,66,46,56,2,40,48,9,0,...,,0,M,0.0,0.00,29.39,30.12,11.7,7,11.9

In [181]:
weather = weather[weather.Station == 1]

In [182]:
weather.columns

Index([u'Station', u'Date', u'Tmax', u'Tmin', u'Tavg', u'Depart', u'DewPoint',
       u'WetBulb', u'Heat', u'Cool', u'Sunrise', u'Sunset', u'CodeSum',
       u'Depth', u'Water1', u'SnowFall', u'PrecipTotal', u'StnPressure',
       u'SeaLevel', u'ResultSpeed', u'ResultDir', u'AvgSpeed'],
      dtype='object')

In [183]:
weather.drop(["CodeSum","Depth","Station", "SnowFall", "Water1"], axis=1, inplace=True)

In [184]:
weather.columns

Index([u'Date', u'Tmax', u'Tmin', u'Tavg', u'Depart', u'DewPoint', u'WetBulb',
       u'Heat', u'Cool', u'Sunrise', u'Sunset', u'PrecipTotal', u'StnPressure',
       u'SeaLevel', u'ResultSpeed', u'ResultDir', u'AvgSpeed'],
      dtype='object')

In [191]:
def eda(dataframe): #Ritkas code chunk to check quality of data
    print "missing values \n", dataframe.isnull().sum() #shows total amount of null values for each column
    print "dataframe types \n", dataframe.dtypes
    print "dataframe shape \n", dataframe.shape     
    print "dataframe describe \n", dataframe.describe()
    print "dataframe length =", len(dataframe) #length of the dataframe
    print "duplicates", dataframe.duplicated().sum() # added this to duplicates in the data
    for item in dataframe:
        print item
        print dataframe[item].nunique()
        
eda(weather)

missing values
Date           0
Tmax           0
Tmin           0
Tavg           0
Depart         0
DewPoint       0
WetBulb        0
Heat           0
Cool           0
Sunrise        0
Sunset         0
PrecipTotal    0
StnPressure    0
SeaLevel       0
ResultSpeed    0
ResultDir      0
AvgSpeed       0
dtype: int64
dataframe types
Date           datetime64[ns]
Tmax                    int64
Tmin                    int64
Tavg                  float64
Depart                float64
DewPoint                int64
WetBulb               float64
Heat                  float64
Cool                  float64
Sunrise                object
Sunset                 object
PrecipTotal           float64
StnPressure            object
SeaLevel               object
ResultSpeed           float64
ResultDir               int64
AvgSpeed               object
dtype: object
dataframe shape
(1472, 17)
dataframe describe
             Tmax         Tmin         Tavg       Depart     DewPoint  \
count  1472.00000  1472.000000  1472.000000  1472.000000  1472.000000
mean     75.97894    56.730978    66.606658     1.954484    53.377717
std      11.50315    10.347907    10.511437     6.841110    10.670263
min      42.00000    29.000000    36.000000   -17.000000    22.000000
25%      68.00000    49.000000    60.000000    -3.000000    46.000000
50%      78.00000    58.000000    68.000000     2.000000    54.000000
75%      85.00000    65.000000    75.000000     7.000000    61.250000
max     103.00000    82.000000    93.000000    23.000000    75.000000

           WetBulb         Heat         Cool  PrecipTotal  ResultSpeed  \
count  1472.000000  1472.000000  1472.000000  1472.000000  1472.000000
mean     59.051630     3.631114     5.237772     0.134538     6.987092
std       9.320856     6.133829     5.899382     0.421066     3.586353
min      32.000000     0.000000     0.000000     0.000000     0.100000
25%      53.000000     0.000000     0.000000     0.000000     4.400000
50%      60.000000     0.000000     3.000000     0.000000     6.400000
75%      66.000000     5.000000    10.000000     0.060000     9.100000
max      78.000000    29.000000    28.000000     6.860000    24.100000

         ResultDir
count  1472.000000
mean     17.656250
std      10.222077
min       1.000000
25%       7.000000
50%      19.500000
75%      26.000000
max      36.000000
dataframe length = 1472
duplicates 0
Date
1472
Tmax
60
Tmin
53
Tavg
56
Depart
41
DewPoint
54
WetBulb
47
Heat
30
Cool
27
Sunrise
121
Sunset
118
PrecipTotal
125
StnPressure
94
SeaLevel
97
ResultSpeed
180
ResultDir
36
AvgSpeed
164

In [186]:
weather[weather['Tavg'] == 'M']
weather.ix[weather.Tavg == "M", "Tavg"] = ((weather.Tmax + weather.Tmin)/2)
#Mike's piece of code for imputing missing values, this time replacing missing values in Tavg 
# with the average of TMax and TMin

In [188]:
weather.ix[weather.WetBulb == "M", "WetBulb"] = ((weather.Tavg + weather.DewPoint)/2)

In [204]:
weather.Date = pd.to_datetime(weather["Date"])
weather['Tavg']= weather['Tavg'].astype('float')
weather['Heat']= weather['Heat'].astype('float')
weather['Cool']= weather['Cool'].astype('float')
weather['Depart']= weather['Depart'].astype('float')
weather['WetBulb']= weather['WetBulb'].astype('float')
weather.fillna(method='pad')
weather['SeaLevel']= weather['SeaLevel'].astype('float')
weather['StnPressure']= weather['StnPressure'].astype('float')

In [189]:
weather.PrecipTotal = weather.PrecipTotal.str.replace(r'T', '0').astype(float)

In [200]:
weather.StnPressure = weather.StnPressure.str.replace(r'M', 'NaN')

In [203]:
weather.SeaLevel = weather.SeaLevel.str.replace(r'M', 'NaN')

In [205]:
weather.corr()

,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir
Tmax,1.000000,0.851965,0.966207,0.683311,0.803170,0.904997,-0.867658,0.819434,0.041751,-0.150681,-0.179273,-0.187049,0.034667
Tmin,0.851965,1.000000,0.957567,0.578054,0.913338,0.953239,-0.820863,0.852695,0.127415,-0.235055,-0.272383,-0.112225,0.009511
Tavg,0.966207,0.957567,1.000000,0.658357,0.888062,0.963578,-0.878719,0.868146,0.085286,-0.198341,-0.232269,-0.158167,0.024257
Depart,0.683311,0.578054,0.658357,1.000000,0.554093,0.612308,-0.525621,0.626541,0.065823,-0.269351,-0.277593,0.020585,0.107721
DewPoint,0.803170,0.913338,0.888062,0.554093,1.000000,0.973394,-0.783307,0.767900,0.228370,-0.302550,-0.329853,-0.191599,0.013438
WetBulb,0.904997,0.953239,0.963578,0.612308,0.973394,1.000000,-0.854771,0.828149,0.167051,-0.257691,-0.288195,-0.181671,0.018352
Heat,-0.867658,-0.820863,-0.878719,-0.525621,-0.783307,-0.854771,1.000000,-0.525949,-0.065560,0.167860,0.196932,0.207425,0.068331
Cool,0.819434,0.852695,0.868146,0.626541,0.767900,0.828149,-0.525949,1.000000,0.083796,-0.178844,-0.209210,-0.066151,0.114267
PrecipTotal,0.041751,0.127415,0.085286,0.065823,0.228370,0.167051,-0.065560,0.083796,1.000000,-0.256333,-0.247023,-0.029755,0.055047
StnPressure,-0.150681,-0.235055,-0.198341,-0.269351,-0.302550,-0.257691,0.167860,-0.178844,-0.256333,1.000000,0.993641,-0.225327,-0.235858
SeaLevel,-0.179273,-0.272383,-0.232269,-0.277593,-0.329853,-0.288195,0.196932,-0.209210,-0.247023,0.993641,1.000000,-0.222559,-0.244752
ResultSpeed,-0.187049,-0.112225,-0.158167,0.020585,-0.191599,-0.181671,0.207425,-0.066151,-0.029755,-0.225327,-0.222559,1.000000,0.094227
ResultDir,0.034667,0.009511,0.024257,0.107721,0.013438,0.018352,0.068331,0.114267,0.055047,-0.235858,-0.244752,0.094227,1.000000

In [206]:
weather.to_csv('../assets/clean_weather.csv')