In [9]:
import pandas as pd
import numpy as np

In [10]:
weather = pd.read_csv("../assets/clean_weather.csv", index_col=0)
train = pd.read_csv("../assets/clean_train.csv", index_col=0)

In [11]:
weather.head()

,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Sunrise,Sunset,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,2007-05-01,83,50,67.0,14.0,51,56.0,0.0,2.0,448,1849,0.00,29.10,29.82,1.7,27,9.2
2,2007-05-02,59,42,51.0,-3.0,42,47.0,14.0,0.0,447,1850,0.00,29.38,30.09,13.0,4,13.4
4,2007-05-03,66,46,56.0,2.0,40,48.0,9.0,0.0,446,1851,0.00,29.39,30.12,11.7,7,11.9
6,2007-05-04,66,49,58.0,4.0,41,50.0,7.0,0.0,444,1852,T,29.31,30.05,10.4,8,10.8
8,2007-05-05,66,53,60.0,5.0,38,49.0,5.0,0.0,443,1853,T,29.40,30.10,11.7,7,12.0

In [12]:
train.head()

,Date,Species,Trap,Latitude,Longitude,NumMosquitos,WnvPresent,Year,Parent_Trap,Is_Satellite,Mos_WNV_Prob,Trap_Ever_Wnv,Num_Years_Trap_WNV_Detection,Max_One_Year_Trap_WNV_Detections,Total_Train_Trap_WNV_Detections,Trap_WNV_Prob
0,2007-05-29,CULEX PIPIENS/RESTUANS,T002,41.954690,-87.800991,1.0,0.0,2007.0,T002,0.0,0.058808,1.0,4,7.0,15.0,0.102041
1,2007-05-29,CULEX RESTUANS,T002,41.954690,-87.800991,1.0,0.0,2007.0,T002,0.0,0.020059,1.0,4,7.0,15.0,0.102041
2,2007-05-29,CULEX RESTUANS,T007,41.994991,-87.769279,1.0,0.0,2007.0,T007,0.0,0.020059,0.0,0,0.0,0.0,0.000000
3,2007-05-29,CULEX PIPIENS/RESTUANS,T015,41.974089,-87.824812,1.0,0.0,2007.0,T015,0.0,0.058808,1.0,1,4.0,4.0,0.125000
4,2007-05-29,CULEX RESTUANS,T015,41.974089,-87.824812,4.0,0.0,2007.0,T015,0.0,0.020059,1.0,1,4.0,4.0,0.125000

In [6]:
train_weather = pd.merge(["weather", "train"], left_on= "Date", right_on= "Date")

TypeError: merge() takes at least 2 arguments (3 given)